// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppDemo.ServiceDefaults.Models22;

[Table("BusinessUnits", Schema = "XLPP")]
[Index("BusinessStructureId", Name = "UQ_XLPP_BusinessUnits_BusinessStructureId", IsUnique = true)]
public partial class BusinessUnit
{
    [Key]
    public int Id { get; set; }

    public Guid BusinessStructureId { get; set; }

    public int? ImportSystemId { get; set; }

    public int? ExportSystemId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    [Required]
    [StringLength(254)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Modified { get; set; }

    [Required]
    [StringLength(254)]
    public string ModifiedBy { get; set; }

    [InverseProperty("BusinessUnit")]
    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();

    [InverseProperty("DefaultBusinessUnit")]
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}