// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppDemo.ServiceDefaults.Models22;

[Table("dhh_BusinessStructures", Schema = "XLPP")]
public partial class DhhBusinessStructure
{
    [Key]
    public Guid Id { get; set; }

    public Guid? ParentStructureId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    [Column("IsDHH")]
    public bool IsDhh { get; set; }

    [Column("IsDHC")]
    public bool IsDhc { get; set; }

    [Column("IsDHP")]
    public bool IsDhp { get; set; }

    public bool? HasLaboratory { get; set; }

    public bool IsArchive { get; set; }

    public bool IsLegalEntity { get; set; }

    public Guid? CountryId { get; set; }

    public int CurrentTreeLevel { get; set; }

    public bool? CopyCodeMasksValuesFromParent { get; set; }

    public bool? CopyTolerancesValuesFromParent { get; set; }

    [Column("BusinessUnitID")]
    public string BusinessUnitId { get; set; }

    [Column("DHPVersion")]
    public string Dhpversion { get; set; }

    public Guid? AuthorizedImportSourceId { get; set; }

    public bool ItemVersionPerPlant { get; set; }

    [Required]
    [StringLength(128)]
    public string Discriminator { get; set; }

    [StringLength(50)]
    public string DefaultCurrency { get; set; }
}