// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppDemo.ServiceDefaults.Models22;

[Table("dhh_BestmixItemLinks", Schema = "XLPP")]
public partial class DhhBestmixItemLink
{
    [Key]
    public Guid Id { get; set; }

    public Guid BestmixItemId { get; set; }

    public Guid ItemId { get; set; }
}