// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppDemo.ServiceDefaults.Models22;

[Table("dhh_BestmixItems", Schema = "XLPP")]
[Index("ExternalId", "ImportSourceId", Name = "UniqueByExternalIdAndImportSource", IsUnique = true)]
public partial class DhhBestmixItem
{
    [Key]
    public Guid Id { get; set; }

    public int ExternalId { get; set; }

    [Required]
    [StringLength(255)]
    public string Code { get; set; }

    public string Name { get; set; }

    public bool IsMapped { get; set; }

    public Guid ImportSourceId { get; set; }

    public bool IsHidden { get; set; }
}