// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppDemo.ServiceDefaults.Models22;

[Table("dhh_Items", Schema = "XLPP")]
public partial class DhhItem1
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(255)]
    public string Code { get; set; }

    public string Name { get; set; }

    public bool IsArchive { get; set; }

    public Guid BusinessStructureId { get; set; }

    public int ImportType { get; set; }

    public bool IsHidden { get; set; }
}