// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppDemo.ServiceDefaults.Models22;

[Table("dhh_ProductionAreas", Schema = "XLPP")]
public partial class DhhProductionArea
{
    [Key]
    public Guid Id { get; set; }

    public int ExternalId { get; set; }

    public string Name { get; set; }

    public int HistoricalPriceListNumber { get; set; }

    public bool UseBestMixLabel { get; set; }

    public bool UseLabelTemplate { get; set; }

    public bool UseLabelExpiration { get; set; }

    public int SalesPriceListNumber { get; set; }

    public bool IsContaminationActive { get; set; }
}