// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppDemo.ServiceDefaults.Models22;

[Table("dhh_PriceTypeConfigurations", Schema = "XLPP")]
[Index("Name", "BusinessStructureId", Name = "UniqueByNameAndBusinessStructure", IsUnique = true)]
public partial class DhhPriceTypeConfiguration
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(256)]
    public string Name { get; set; }

    public Guid BusinessStructureId { get; set; }

    public int CurrentPriceBestmixId { get; set; }

    public int PriceMonth1BestmixId { get; set; }

    public int PriceMonth2BestmixId { get; set; }

    public int PriceMonth3BestmixId { get; set; }

    public int PriceMonth4BestmixId { get; set; }

    public int PriceMonth5BestmixId { get; set; }

    public int PriceMonth6BestmixId { get; set; }

    public int PriceMonth7BestmixId { get; set; }

    public int PriceMonth8BestmixId { get; set; }

    public int PriceMonth9BestmixId { get; set; }

    public int PriceMonth10BestmixId { get; set; }

    public int PriceMonth11BestmixId { get; set; }

    public bool IsArchive { get; set; }

    public string CreateUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    public string UpdateUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public int? LegacyPriceType { get; set; }

    public bool UseCurrentMonthOnly { get; set; }
}