// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppDemo.ServiceDefaults.Models22;

[Table("Jobs", Schema = "XLPP")]
public partial class Job
{
    [Key]
    public int Id { get; set; }

    public int JobTypeId { get; set; }

    public int JobStatusId { get; set; }

    public int BusinessUnitId { get; set; }

    [Column("PriceTypeID")]
    public int PriceTypeId { get; set; }

    [Column("DataSourceID")]
    public int? DataSourceId { get; set; }

    [StringLength(254)]
    public string ExecutionId { get; set; }

    [StringLength(128)]
    public string ExecutionStatus { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    [Required]
    [StringLength(254)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Modified { get; set; }

    [Required]
    [StringLength(254)]
    public string ModifiedBy { get; set; }

    public string AdditionalInformation { get; set; }

    [ForeignKey("BusinessUnitId")]
    [InverseProperty("Jobs")]
    public virtual BusinessUnit BusinessUnit { get; set; }

    [ForeignKey("JobStatusId")]
    [InverseProperty("Jobs")]
    public virtual JobStatus JobStatus { get; set; }

    [ForeignKey("JobTypeId")]
    [InverseProperty("Jobs")]
    public virtual JobType JobType { get; set; }
}