// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppDemo.ServiceDefaults.Models22;

[Table("Systems", Schema = "XLPP")]
[Index("Name", "BusinessStructureId", Name = "UQ_XLPP_Systems_Name_BusinessStructureId", IsUnique = true)]
public partial class System
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(150)]
    public string Name { get; set; }

    public Guid? BusinessStructureId { get; set; }

    public bool IsImportSystem { get; set; }

    public bool IsExportSystem { get; set; }

    public bool AllowPricesToBeChanged { get; set; }

    public int? JobTypeId { get; set; }

    public bool HasHistoricPrices { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    [Required]
    [StringLength(254)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Modified { get; set; }

    [Required]
    [StringLength(254)]
    public string ModifiedBy { get; set; }
}