// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppDemo.ServiceDefaults.Models22;

[Table("Users", Schema = "XLPP")]
[Index("Username", Name = "UQ_XLPP_Users_Username", IsUnique = true)]
public partial class User
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(254)]
    public string Username { get; set; }

    public int? DefaultBusinessUnitId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastAccessDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    [Required]
    [StringLength(254)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Modified { get; set; }

    [Required]
    [StringLength(254)]
    public string ModifiedBy { get; set; }

    [ForeignKey("DefaultBusinessUnitId")]
    [InverseProperty("Users")]
    public virtual BusinessUnit DefaultBusinessUnit { get; set; }
}