// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppDemo.ServiceDefaults.Models;

public partial class DataSource
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public byte? Active { get; set; }
}