// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppDemo.ServiceDefaults.Models;

public partial class DhhBusinessStructure
{
    public string Id { get; set; }

    public string ParentStructureId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool? IsDhh { get; set; }

    public bool? IsDhc { get; set; }

    public bool? IsDhp { get; set; }

    public bool? HasLaboratory { get; set; }

    public bool? IsArchive { get; set; }

    public bool? IsLegalEntity { get; set; }

    public string CountryId { get; set; }

    public int? CurrentTreeLevel { get; set; }

    public bool? CopyCodeMasksValuesFromParent { get; set; }

    public bool? CopyTolerancesValuesFromParent { get; set; }

    public string BusinessUnitId { get; set; }

    public string Dhpversion { get; set; }

    public string AuthorizedImportSourceId { get; set; }

    public bool? ItemVersionPerPlant { get; set; }

    public string Discriminator { get; set; }
}