// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppDemo.ServiceDefaults.Models;

public partial class DhhBestmixItem
{
    public string Id { get; set; }

    public int? ExternalId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public bool? IsMapped { get; set; }

    public string ImportSourceId { get; set; }

    public bool? IsHidden { get; set; }
}