// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppDemo.ServiceDefaults.Models;

public partial class DhhBestmixItemLink
{
    public string Id { get; set; }

    public string BestmixItemId { get; set; }

    public string ItemId { get; set; }
}