// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppDemo.ServiceDefaults.Models;

public partial class DhhCountry
{
    public string Id { get; set; }

    public string TwoLettersIsocode { get; set; }

    public string EnglishName { get; set; }
}