// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppDemo.ServiceDefaults.Models;

public partial class Dhhdatum
{
    public string BusinessStructureId { get; set; }

    public string BuName { get; set; }

    public string ProductionAreaId { get; set; }

    public string ProductionArea { get; set; }

    public string PriceTypeConfigurationId { get; set; }

    public string PriceType { get; set; }

    public string LegacyPriceType { get; set; }
}