// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppDemo.ServiceDefaults.Models;

public partial class DhhItem1
{
    public string Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public bool? IsArchive { get; set; }

    public string BusinessStructureId { get; set; }

    public int? ImportType { get; set; }

    public bool? IsHidden { get; set; }
}