// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppDemo.ServiceDefaults.Models;

public partial class Dhhitem
{
    public string BusinessStructureId { get; set; }

    public string BuName { get; set; }

    public string IngredientNumber { get; set; }

    public string GlobalCodes { get; set; }

    public string Responsible { get; set; }

    public string ProductName { get; set; }
}