// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppDemo.ServiceDefaults.Models;

public partial class DhhPriceTypeConfiguration
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string BusinessStructureId { get; set; }

    public int? CurrentPriceBestmixId { get; set; }

    public int? PriceMonth1BestmixId { get; set; }

    public int? PriceMonth2BestmixId { get; set; }

    public int? PriceMonth3BestmixId { get; set; }

    public int? PriceMonth4BestmixId { get; set; }

    public int? PriceMonth5BestmixId { get; set; }

    public int? PriceMonth6BestmixId { get; set; }

    public int? PriceMonth7BestmixId { get; set; }

    public int? PriceMonth8BestmixId { get; set; }

    public int? PriceMonth9BestmixId { get; set; }

    public int? PriceMonth10BestmixId { get; set; }

    public int? PriceMonth11BestmixId { get; set; }

    public bool? IsArchive { get; set; }

    public string CreateUser { get; set; }

    public DateTime? CreateDate { get; set; }

    public string UpdateUser { get; set; }

    public DateTime? UpdateDate { get; set; }

    public int? LegacyPriceType { get; set; }

    public bool? UseCurrentMonthOnly { get; set; }
}