// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebAppDemo.ServiceDefaults.Models;

namespace WebAppDemo.ServiceDefaults.Models
{
    public partial interface ItestxluploadContextProcedures
    {
        Task<List<cleanUploadedXLPurchasePricesResult>> cleanUploadedXLPurchasePricesAsync(int? daysBack, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<getBuTemplateDataResult>> getBuTemplateDataAsync(string BuName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<getNewJobDetailsResult>> getNewJobDetailsAsync(int? BusinessUnitId, string SystemName, string JobType, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<getUploadedXLPurchasePriceHeadersResult>> getUploadedXLPurchasePriceHeadersAsync(int? daysBack, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<getUploadedXLPurchasePricesResult>> getUploadedXLPurchasePricesAsync(Guid? BusinessStructureId, Guid? PriceTypeConfigurationId, DateOnly? WeekNumberDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> mergeXLPurchasePricesAsync(string FileName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
