// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppDemo.ServiceDefaults.Models;

public partial class Job
{
    public int Id { get; set; }

    public int JobTypeId { get; set; }

    public int JobStatusId { get; set; }

    public int BusinessUnitId { get; set; }

    public int PriceTypeId { get; set; }

    public int? DataSourceId { get; set; }

    public string ExecutionId { get; set; }

    public string ExecutionStatus { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime Modified { get; set; }

    public string ModifiedBy { get; set; }

    public virtual BusinessUnit BusinessUnit { get; set; }

    public virtual JobStatus JobStatus { get; set; }

    public virtual JobType JobType { get; set; }
}