// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppDemo.ServiceDefaults.Models;

public partial class JobStatus
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();
}