// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppDemo.ServiceDefaults.Models;

public partial class PriceType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string ParamPage { get; set; }

    public string ParamPricetype { get; set; }

    public int? LegacyPricetype { get; set; }

    public byte? Active { get; set; }
}