// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using WebAppDemo.ServiceDefaults.Models;

namespace WebAppDemo.ServiceDefaults.Models
{
    public partial class testxluploadContext
    {

        [DbFunction("convertCurrencyValue", "dbo")]
        public static decimal? convertCurrencyValue(string SourceCurrency, string TargetCurrency, decimal? Value)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
