// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebAppDemo.ServiceDefaults.Models;

namespace WebAppDemo.ServiceDefaults.Models
{
    public partial class testxluploadContext
    {
        private ItestxluploadContextProcedures _procedures;

        public virtual ItestxluploadContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new testxluploadContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ItestxluploadContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class testxluploadContextProcedures : ItestxluploadContextProcedures
    {
        private readonly testxluploadContext _context;

        public testxluploadContextProcedures(testxluploadContext context)
        {
            _context = context;
        }

        public virtual async Task<List<cleanUploadedXLPurchasePricesResult>> cleanUploadedXLPurchasePricesAsync(int? daysBack, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "daysBack",
                    Value = daysBack ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<cleanUploadedXLPurchasePricesResult>("EXEC @returnValue = [dbo].[cleanUploadedXLPurchasePrices] @daysBack = @daysBack", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<getBuTemplateDataResult>> getBuTemplateDataAsync(string BuName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "BuName",
                    Size = -1,
                    Value = BuName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<getBuTemplateDataResult>("EXEC @returnValue = [dbo].[getBuTemplateData] @BuName = @BuName", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<getNewJobDetailsResult>> getNewJobDetailsAsync(int? BusinessUnitId, string SystemName, string JobType, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "BusinessUnitId",
                    Value = BusinessUnitId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "SystemName",
                    Size = 300,
                    Value = SystemName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "JobType",
                    Size = 300,
                    Value = JobType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<getNewJobDetailsResult>("EXEC @returnValue = [XLPP].[getNewJobDetails] @BusinessUnitId = @BusinessUnitId, @SystemName = @SystemName, @JobType = @JobType", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<getUploadedXLPurchasePriceHeadersResult>> getUploadedXLPurchasePriceHeadersAsync(int? daysBack, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "daysBack",
                    Value = daysBack ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<getUploadedXLPurchasePriceHeadersResult>("EXEC @returnValue = [dbo].[getUploadedXLPurchasePriceHeaders] @daysBack = @daysBack", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<getUploadedXLPurchasePricesResult>> getUploadedXLPurchasePricesAsync(Guid? BusinessStructureId, Guid? PriceTypeConfigurationId, DateOnly? WeekNumberDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "BusinessStructureId",
                    Value = BusinessStructureId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "PriceTypeConfigurationId",
                    Value = PriceTypeConfigurationId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "WeekNumberDate",
                    Value = WeekNumberDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<getUploadedXLPurchasePricesResult>("EXEC @returnValue = [dbo].[getUploadedXLPurchasePrices] @BusinessStructureId = @BusinessStructureId, @PriceTypeConfigurationId = @PriceTypeConfigurationId, @WeekNumberDate = @WeekNumberDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> mergeXLPurchasePricesAsync(string FileName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "FileName",
                    Size = 520,
                    Value = FileName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[mergeXLPurchasePrices] @FileName = @FileName", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
