// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppDemo.ServiceDefaults.Models;

public partial class User
{
    public int Id { get; set; }

    public string Username { get; set; }

    public int? DefaultBusinessUnitId { get; set; }

    public DateTime LastAccessDate { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime Modified { get; set; }

    public string ModifiedBy { get; set; }

    public virtual BusinessUnit DefaultBusinessUnit { get; set; }
}