// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppDemo.ServiceDefaults.Models;

public partial class XlpurchasePricesTemp
{
    public long XlpurchasePriceId { get; set; }

    public string ItemCode { get; set; }

    public string GlobalCode { get; set; }

    public string Responsible { get; set; }

    public string ProductName { get; set; }

    public string YearMonth { get; set; }

    public DateOnly YearMonthDate { get; set; }

    public decimal? PriceValue { get; set; }

    public string BusinessUnitName { get; set; }

    public string PriceTypeName { get; set; }

    public string WeekNumber { get; set; }

    public DateOnly WeekNumberDate { get; set; }

    public string FileName { get; set; }

    public DateTime CreatedDate { get; set; }

    public string LegacyPriceType { get; set; }

    public string CurrencyCode { get; set; }

    public string ProductionAreaName { get; set; }
}