// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppDemo.ServiceDefaults.Models;

public partial class XlpurchasePricesCurrencyValue
{
    public int XlpurchasePricesCurrencyValueId { get; set; }

    public string SourceCurrency { get; set; }

    public string TargetCurrency { get; set; }

    public decimal Value { get; set; }

    public DateTime LastCloseDate { get; set; }
}