// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppDemo.ServiceDefaults.Models;

public partial class XlpurchasePricesCurrencyCode
{
    public int XlpurchasePricesCurrencyCodeId { get; set; }

    public string CurrencyCode { get; set; }

    public string CurrencyName { get; set; }
}