// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAppDemo.ServiceDefaults.Models;

public partial class XlpurchasePricesProductionAreasTemp
{
    public long XlpurchasePricesProductionAreaId { get; set; }

    public string ProductionAreaName { get; set; }

    public string FileName { get; set; }

    public DateTime CreatedDate { get; set; }
}