// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppDemo.ServiceDefaults.Models22;

[Table("BusinessUnitPriceDataSource")]
[Index("BusinessUnitId", "PriceTypeId", "DataSourceId", Name = "UQ__Business__4B911781A294A92C", IsUnique = true)]
public partial class BusinessUnitPriceDataSource
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("BusinessUnitID")]
    public int? BusinessUnitId { get; set; }

    [Column("PriceTypeID")]
    public int? PriceTypeId { get; set; }

    [Column("DataSourceID")]
    public int? DataSourceId { get; set; }

    [Column("export_filepath")]
    [StringLength(250)]
    [Unicode(false)]
    public string ExportFilepath { get; set; }

    [Column("notification")]
    [StringLength(250)]
    [Unicode(false)]
    public string Notification { get; set; }
}