// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppDemo.ServiceDefaults.Models22;

[Table("dhhitems")]
public partial class Dhhitem
{
    [Key]
    [Column("Item_Key")]
    public long ItemKey { get; set; }

    public Guid BusinessStructureId { get; set; }

    [Required]
    public string BuName { get; set; }

    [Required]
    [Column("Ingredient Number")]
    [StringLength(255)]
    public string IngredientNumber { get; set; }

    [Required]
    [Column("Global Codes")]
    [StringLength(255)]
    public string GlobalCodes { get; set; }

    [StringLength(400)]
    public string Responsible { get; set; }

    [Column("Product Name")]
    public string ProductName { get; set; }

    [Required]
    [StringLength(255)]
    public string ItemGroupCode { get; set; }

    [Required]
    public string ItemGroup { get; set; }
}