// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAppDemo.ServiceDefaults.Models22
{
    public partial class getBuTemplateData2Result
    {
        [Column("Ingredient Number")]
        public string IngredientNumber { get; set; }
        [Column("Global Codes")]
        public string GlobalCodes { get; set; }
        public string Responsible { get; set; }
        [Column("Product Name")]
        public string ProductName { get; set; }
        [Column("Currency Code")]
        public int? CurrencyCode { get; set; }
        [Column("2024-09-01 00:00:00")]
        public int? _20240901000000 { get; set; }
        [Column("2024-10-01 00:00:00")]
        public int? _20241001000000 { get; set; }
        [Column("2024-11-01 00:00:00")]
        public int? _20241101000000 { get; set; }
        [Column("2024-12-01 00:00:00")]
        public int? _20241201000000 { get; set; }
        [Column("2025-01-01 00:00:00")]
        public int? _20250101000000 { get; set; }
        [Column("2025-02-01 00:00:00")]
        public int? _20250201000000 { get; set; }
        [Column("2025-03-01 00:00:00")]
        public int? _20250301000000 { get; set; }
        [Column("2025-04-01 00:00:00")]
        public int? _20250401000000 { get; set; }
        [Column("2025-05-01 00:00:00")]
        public int? _20250501000000 { get; set; }
        [Column("2025-06-01 00:00:00")]
        public int? _20250601000000 { get; set; }
        [Column("2025-07-01 00:00:00")]
        public int? _20250701000000 { get; set; }
        [Column("2025-08-01 00:00:00")]
        public int? _20250801000000 { get; set; }
    }
}
