// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppDemo.ServiceDefaults.Models22;

[Keyless]
public partial class IntDefaultCurrency
{
    public Guid BusinessStructureId { get; set; }

    public string BusinessUnitName { get; set; }

    [StringLength(50)]
    public string DefaultCurrency { get; set; }
}