// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppDemo.ServiceDefaults.Models22;

public partial class PriceType
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column(TypeName = "text")]
    public string Description { get; set; }

    [Column("param_page")]
    [StringLength(50)]
    [Unicode(false)]
    public string ParamPage { get; set; }

    [Column("param_pricetype")]
    [StringLength(50)]
    [Unicode(false)]
    public string ParamPricetype { get; set; }

    [Column("legacy_pricetype")]
    public int? LegacyPricetype { get; set; }

    public byte? Active { get; set; }
}