// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppDemo.ServiceDefaults.Models22;

[Table("XLPurchasePricesProductionAreas_Temp")]
[Index("FileName", Name = "IX_XLPurchasePricesProductionAreas_Temp_FileName")]
public partial class XlpurchasePricesProductionAreasTemp
{
    [Key]
    [Column("XLPurchasePricesProductionArea_id")]
    public long XlpurchasePricesProductionAreaId { get; set; }

    [Required]
    public string ProductionAreaName { get; set; }

    [Required]
    [StringLength(260)]
    public string FileName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }
}