// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppDemo.ServiceDefaults.Models22;

[Table("XLPurchasePrices")]
[Index("WeekNumberDate", Name = "NC_XLPurchasePrices_WeekNumberDate")]
public partial class XlpurchasePrice
{
    [Key]
    [Column("XLPurchasePrice_id")]
    public long XlpurchasePriceId { get; set; }

    [Required]
    [StringLength(255)]
    public string ItemCode { get; set; }

    [Required]
    [StringLength(255)]
    public string GlobalCode { get; set; }

    [StringLength(400)]
    public string Responsible { get; set; }

    public string ProductName { get; set; }

    [Required]
    [StringLength(7)]
    public string YearMonth { get; set; }

    public DateOnly YearMonthDate { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal? PriceValue { get; set; }

    [Required]
    public string BusinessUnitName { get; set; }

    [Required]
    [StringLength(256)]
    public string PriceTypeName { get; set; }

    [Required]
    public string ProductionAreaName { get; set; }

    [Required]
    [StringLength(7)]
    public string WeekNumber { get; set; }

    public DateOnly WeekNumberDate { get; set; }

    [Required]
    [StringLength(260)]
    public string FileName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ModifiedDate { get; set; }

    [Required]
    [StringLength(256)]
    public string LegacyPriceType { get; set; }

    public Guid BusinessStructureId { get; set; }

    public Guid? PriceTypeConfigurationId { get; set; }

    public Guid ProductionAreaId { get; set; }

    [Required]
    [StringLength(3)]
    public string CurrencyCode { get; set; }
}