// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebAppDemo.ServiceDefaults.Models22;

namespace WebAppDemo.ServiceDefaults.Models22
{
    public partial interface Itest2xluploadContextProcedures
    {
        Task<List<getBuTemplateDataResult>> getBuTemplateDataAsync(string BuName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<getBuTemplateData2Result>> getBuTemplateData2Async(string BuName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<getUploadedXLPurchasePriceHeadersResult>> getUploadedXLPurchasePriceHeadersAsync(int? daysBack, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> mergeXLPurchasePricesAsync(string FileName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
