// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using WebAppDemo.ServiceDefaults.Models22;

namespace WebAppDemo.ServiceDefaults.Models22
{
    public partial class test2xluploadContext
    {

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
